version: '3.8'

services:
  db:
    image: mongo:4.4
    container_name: main_mongo
    restart: unless-stopped
    volumes:
      - main-mongo-data:/data/db
      - main-mongo-config:/data/configdb
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  backend:
    build:  ./main_backend
    container_name: main_backend
    command: "java -jar /app.jar"
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - db
volumes:
  main-mongo-data:
  main-mongo-config:
